import { ACTIONS, SolanaAgentKit, startMcpServer } from "solana-agent-kit";
import * as dotenv from "dotenv";

dotenv.config();

const agent = new SolanaAgentKit(
    process.env.SOLANA_PRIVATE_KEY!,
    process.env.RPC_URL!,
    {
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
    },
);

// Add your required actions here
const mcp_actions = {
    // 基础actions
    GET_ASSET: ACTIONS.GET_ASSET_ACTION,
    DEPLOY_TOKEN: ACTIONS.DEPLOY_TOKEN_ACTION,
    FETCH_PRICE: ACTIONS.FETCH_PRICE_ACTION,
    GET_ALL_TOPICS: ACTIONS.GET_ALL_TOPICS_ACTION,
    GET_PRICE_INFERENCE: ACTIONS.GET_PRICE_INFERENCE_ACTION,
    WALLET_ADDRESS: ACTIONS.WALLET_ADDRESS_ACTION,
    TOKEN_BALANCES: ACTIONS.TOKEN_BALANCES_ACTION,
    BALANCE: ACTIONS.BALANCE_ACTION,
    // Removed the problematic action SOLUTIOFI_CLOSE_ACCOUNTS
    TRANSFER: ACTIONS.TRANSFER_ACTION,
    
    // Trending tokens和pools相关actions
    ELFA_TRENDING_TOKENS: ACTIONS.ELFA_TRENDING_TOKENS_ACTION,
    GET_COINGECKO_TRENDING_TOKENS: ACTIONS.GET_COINGECKO_TRENDING_TOKENS_ACTION,
    GET_COINGECKO_TRENDING_POOLS: ACTIONS.GET_COINGECKO_TRENDING_POOLS_ACTION,
    GET_COINGECKO_LATEST_POOLS: ACTIONS.GET_COINGECKO_LATEST_POOLS_ACTION,
    GET_COINGECKO_TOP_GAINERS: ACTIONS.GET_COINGECKO_TOP_GAINERS_ACTION,
    
    // ELFA市场洞察和话题分析
    ELFA_PING: ACTIONS.ELFA_PING_ACTION,
    ELFA_API_KEY_STATUS: ACTIONS.ELFA_API_KEY_STATUS_ACTION,
    ELFA_GET_SMART_MENTIONS: ACTIONS.ELFA_GET_SMART_MENTIONS_ACTION,
    ELFA_GET_TOP_MENTIONS_BY_TICKER: ACTIONS.ELFA_GET_TOP_MENTIONS_BY_TICKER_ACTION,
    ELFA_SEARCH_MENTIONS_BY_KEYWORDS: ACTIONS.ELFA_SEARCH_MENTIONS_BY_KEYWORDS_ACTION,
    ELFA_SMART_TWITTER_ACCOUNT_STATS: ACTIONS.ELFA_SMART_TWITTER_ACCOUNT_STATS_ACTION,
    
    // Pool相关actions
    CREATE_ORCA_SINGLE_SIDED_WHIRLPOOL: ACTIONS.CREATE_ORCA_SINGLE_SIDED_WHIRLPOOL_ACTION,
    FLUXBEAM_CREATE_POOL: ACTIONS.FLUXBEAM_CREATE_POOL_ACTION
};

// Use a type assertion to bypass type checking
startMcpServer(mcp_actions as any, agent, { name: "quant72-mcp", version: "0.1.0" });
